# Generated by Django 4.2.4 on 2023-08-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
