# Generated by Django 4.2.4 on 2023-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0002_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_in',
            field=models.BooleanField(default=False),
        ),
    ]
