# Generated by Django 4.2.5 on 2023-09-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0003_player_is_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_in',
        ),
    ]
