# Generated by Django 4.2.7 on 2023-11-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0004_remove_player_is_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToeMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq00', models.PositiveSmallIntegerField(default=0)),
                ('sq01', models.PositiveSmallIntegerField(default=0)),
                ('sq02', models.PositiveSmallIntegerField(default=0)),
                ('sq10', models.PositiveSmallIntegerField(default=0)),
                ('sq11', models.PositiveSmallIntegerField(default=0)),
                ('sq12', models.PositiveSmallIntegerField(default=0)),
                ('sq20', models.PositiveSmallIntegerField(default=0)),
                ('sq21', models.PositiveSmallIntegerField(default=0)),
                ('sq22', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='ground.tictactoematrix')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='ground.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='ground.player')),
            ],
        ),
    ]
