# Generated by Django 4.2.4 on 2023-11-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0005_tictactoematrix_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='ground.tictactoematrix'),
        ),
    ]
